# Generated by Django 3.2.4 on 2021-06-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='number_of_questions',
            field=models.IntegerField(help_text='number of questions'),
        ),
    ]
