# Generated by Django 3.2.4 on 2021-09-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('regno', models.CharField(max_length=200)),
                ('marks', models.IntegerField(help_text='number of questions')),
                ('time', models.IntegerField(help_text='duration of exam in munites')),
                ('required_score_to_pass', models.IntegerField(help_text='required score in % ')),
            ],
        ),
    ]
